.PHONY: clean All

All:
	@echo "----------Building project:[ Autocorrelation_StreamData - Debug ]----------"
	@cd "Autocorrelation_StreamData" && "$(MAKE)" -f  "Autocorrelation_StreamData.mk"
clean:
	@echo "----------Cleaning project:[ Autocorrelation_StreamData - Debug ]----------"
	@cd "Autocorrelation_StreamData" && "$(MAKE)" -f  "Autocorrelation_StreamData.mk" clean
